### ISSUE TITLE
Please document if this will work with China

### ISSUE THREAD

**Issue by strowk** [aws-samples/amazon-ecr-cross-region-replication#5]
I have to deploy to China AWS to region "cn-north-1". Could you please answer if this replication will work with that region (I know that it has ECR, but I also now it's a completely different infrastructure). If this is not designed to work between Europe and China, please document this explicitly. 
Thanks!

**Comment by walkley** [comment]
Please refer to following solution to replicate container images between AWS Europe and China:
https://www.amazonaws.cn/en/solutions/data-replication-hub/

This solution support:

> 3. Replicate Amazon ECR Images between AWS Global regions and China regions.
> 4. Replicate container images from public container registry (e.g., Docker Hub, Google gcr.io, Red Hat Quay.io) to Amazon ECR.

**Comment by strowk** [comment]
Got it, thanks! Do you think it's something to mention in docs as well?

**Comment by GCTheja** [comment]
The page in provided link (https://www.amazonaws.cn/en/solutions/data-replication-hub/) throwing 404 error. I am looking for a solution to replicate container images between AWS US and China. Any advise please?

**Comment by prasanjitshome** [comment]
@walkley : please help provide a solution on this. 3rd party integration should be fine as well.

**Comment by walkley** [comment]
The solution has been renamed to Data Transfer Hub, here is the link: https://www.amazonaws.cn/en/solutions/data-transfer-hub/
